name: "Maintenance Bot"
on:
  - pull_request_target

jobs:
  labeler:
    name: Assign labels and milestone
    runs-on: ubuntu-latest
    env:
      MILESTONE_NUMBER: 18
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Assign milestone
        if: |
          ! github.event.pull_request.milestone &&
          ! contains(github.event.pull_request.labels.*.name, 'merge') &&
          ! contains(github.event.pull_request.labels.*.name, 'status/WIP') &&
          ! contains(github.event.pull_request.title, 'WIP') &&
          ! github.event.pull_request.draft
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue_number,
              milestone: $MILESTONE_NUMBER,
            });
