name: OSX
on: [push, pull_request]
jobs:

  test:
    name: Startup test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'galaxy root'
    - name: Cache pip dir
      uses: actions/cache@v1
      id: pip-cache
      with:
        path: ~/Library/Caches/pip
        # scripts/common_startup.sh creates a conda env for Galaxy containing Python 3.6
        key: pip-cache-3.6-${{ hashFiles('galaxy root/requirements.txt') }}
    - name: Install and activate miniconda  # use this job to test using Python from a conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ''
    - name: conda info
      run: conda info
    - name: run tests
      run: .ci/first_startup.sh
      shell: bash -l {0}  # need this to have CONDA_EXE set
      working-directory: 'galaxy root'
